In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [17]:
# Load the dataset
dataset = pd.read_csv("C:\\Users\\kwany\\Desktop\\ML Final Test\\question1edata.csv")
print("Original Feature Vector")
print(dataset.to_numpy())

Original Feature Vector
[[0.5 0.7]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]
 [1.9 2.2]
 [2.2 2.9]
 [2.6 2.7]
 [2.  1.6]
 [2.5 2.4]
 [3.1 3. ]]


In [6]:
# Features standardization
sc = StandardScaler()
std_dataset = sc.fit_transform(dataset)
std_dataset

array([[-1.740994  , -1.506743  ],
       [-1.09136937, -1.00864614],
       [-0.44174475, -0.38602507],
       [-0.96144445, -1.25769457],
       [ 0.07795496,  0.36112022],
       [ 0.46772973,  1.23278973],
       [ 0.98742943,  0.9837413 ],
       [ 0.20787988, -0.38602507],
       [ 0.85750451,  0.61016865],
       [ 1.63705406,  1.35731394]])

In [18]:
# Construct the covariance matrix
covariance_matrix = np.cov(std_dataset.T)
print("Covariance Matrix")
print(covariance_matrix)

Covariance Matrix
[[1.11111111 1.03831938]
 [1.03831938 1.11111111]]


In [8]:
# Get the eigenvectors and eigenvalues by using the covariance matrix
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [11]:
print("Eigenvalues")
print(eigen_values)
print("")
print("Eigenvector")
print(eigen_vectors)

Eigenvalues
[2.1494305  0.07279173]

Eigenvector
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [20]:
# Obtain the feature vector using eigenvectors
feature_vec = np.dot(std_dataset, eigen_vectors)
print("Feature Vector")
print(feature_vec)

Feature Vector
[[-2.29649685  0.16564047]
 [-1.48493521  0.05849416]
 [-0.58532165  0.03939976]
 [-1.56916825 -0.20948047]
 [ 0.31047304  0.20022808]
 [ 1.20244884  0.54097911]
 [ 1.39382819 -0.0026079 ]
 [-0.12596767 -0.41995421]
 [ 1.03780164 -0.17489286]
 [ 2.11733792 -0.19780613]]


In [26]:
# Calculate cumulative sum of explained variances
tot = sum(eigen_values)
var_exp = [(i / tot) for i in sorted(eigen_values, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

In [13]:
# Make a list of tuples with the structure (eigenvalue, eigenvector)
eigen_pairs = [(np.abs(eigen_values[i]), eigen_vectors[:, i]) for i in range(len(eigen_values))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eigen_pairs.sort(key=lambda k: k[0], reverse=True)

In [14]:
# Print out the ordered eigenpairs
print(eigen_pairs)

[(2.149430495007601, array([0.70710678, 0.70710678])), (0.07279172721462168, array([-0.70710678,  0.70710678]))]


In [27]:
# Choose the eigenvector with the highest eigenvalues.
chosen_eigenvalues = np.hstack((eigen_pairs[0][1][:, np.newaxis]))
print('Chosen Eigen Vector:\n', chosen_eigenvalues)

Chosen Eigen Vector:
 [0.70710678 0.70710678]


In [28]:
# Obtain the 1D dataset
pca_data = std_dataset.dot(w)
pca_data = pca_data.reshape(10, 1)
print("New 1D Dataset")
print(pca_data)

New 1D Dataset
[[-2.29649685]
 [-1.48493521]
 [-0.58532165]
 [-1.56916825]
 [ 0.31047304]
 [ 1.20244884]
 [ 1.39382819]
 [-0.12596767]
 [ 1.03780164]
 [ 2.11733792]]
